# Generated by Django 3.2.8 on 2024-05-16 08:14

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('mobile_image', models.ImageField(default='', upload_to='mobileBanner')),
                ('url', models.URLField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BilingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(upload_to='brandimg')),
                ('brand_url', models.CharField(max_length=200)),
                ('brand_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=320, null=True)),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=320, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('subtotal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('coupon_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('shipping_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=320, null=True)),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=320, null=True)),
                ('category_logo', models.ImageField(blank=True, default=None, null=True, upload_to='categoryimg')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('Address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('facebook_account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('instagram_account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('whatsapp_account', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('discount', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('coupon_expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.ImageField(upload_to='featuredOffer')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('meta_tag_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('meta_tag_keywords', models.TextField(blank=True, null=True)),
                ('meta_tag_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('PENDING', 'PENDING'), ('ON THE WAY', 'ON THE WAY'), ('DELEIVERED', 'DELEIVERED'), ('CANCEL', 'CANCEL'), ('RETURN', 'RETURN')], default='PENDING', max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Manual Bank Transfer', 'Manual Bank Transfer')], max_length=50)),
                ('sub_total', models.PositiveIntegerField(blank=True, null=True)),
                ('flat_shipping_rate', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('biling_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bilingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('SKU_number', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=250)),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField()),
                ('original_selling_price', models.FloatField(editable=False, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('main_picture', models.ImageField(upload_to='mainimg')),
                ('available_stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=50)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('long_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=320, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=320, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=50)),
                ('product_type', models.CharField(blank=True, choices=[('1', 'Simple Product'), ('2', 'Variable Product')], default='1', max_length=50, null=True)),
                ('show_in_bestseller_slider', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=50)),
                ('descripion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.IntegerField()),
                ('bank_account_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=320, null=True)),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=320, null=True)),
                ('subcategory_logo', models.ImageField(blank=True, default='', null=True, upload_to='subcategoryimg')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topCategory')),
                ('url', models.URLField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=320, null=True)),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=320, null=True)),
                ('subsubcategory_logo', models.ImageField(blank=True, default='', null=True, upload_to='subsubcategoryimg')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('parent_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Peshawar', 'Peshawar'), ('Islamabad', 'Islamabad'), ('Quetta', 'Quetta'), ('Faisalabad', 'Faisalabad'), ('Other', 'Other')], max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('area', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.IntegerField()),
                ('Sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], default='DENIED', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default='', null=True)),
                ('attributes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.productattributevalue')),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelatedImages', models.ImageField(upload_to='relatedimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subsubcategory'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_sale_price', models.IntegerField()),
                ('FlashSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coupon'),
        ),
    ]
